### ISSUE TITLE
Latest is not working because of missing openssl

### ISSUE THREAD

**Issue by eapyl** [bringnow/docker-nginx-letsencrypt#4]
Hi, it is a log from docker:
nginx_1            | dhparam file /etc/nginx/dhparam/dhparam.pem does not exist. Generating one with 4086 bit. This will take a while...
nginx_1            | /entrypoint.sh: line 21: openssl: command not found
nginx_1            | Could not generate dhparam file
nginx_1            | dhparam file /etc/nginx/dhparam/dhparam.pem does not exist. Generating one with 4086 bit. This will take a while...
nginx_1            | /entrypoint.sh: line 21: openssl: command not found
nginx_1            | Could not generate dhparam file
nginx_1            | dhparam file /etc/nginx/dhparam/dhparam.pem does not exist. Generating one with 4086 bit. This will take a while...
nginx_1            | /entrypoint.sh: line 21: openssl: command not found
nginx_1            | Could not generate dhparam file
nginx_1            | dhparam file /etc/nginx/dhparam/dhparam.pem does not exist. Generating one with 4086 bit. This will take a while...
nginx_1            | /entrypoint.sh: line 21: openssl: command not found
nginx_1            | Could not generate dhparam file
nginx_1            | dhparam file /etc/nginx/dhparam/dhparam.pem does not exist. Generating one with 4086 bit. This will take a while...
nginx_1            | /entrypoint.sh: line 21: openssl: command not found
nginx_1

**Comment by fkoester** [comment]
Hi, thanks for your report. Which version of the image are you using? Please copy the output of the following command:

```
docker images | grep nginx-letsencrypt
```

**Comment by fkoester** [comment]
Ah, I already see. I also added `openssl` to the list of packages to install for the debian based images. Should be fixed after Docker hub rebuild the images. Please reopen if this is not fixed for you then.
